### ISSUE TITLE
About the PolyFisheyeCamera model

### ISSUE THREAD

**Issue by CanCanZeng** [xuhao1/VINS-Fisheye#1]
Thank you for sharing this great work!
Where can I find the definition of PolyFisheyeCamera model? I mean, is there any document about this camera model?
Can I using other camera model such as fisheye camera model in opencv? The FOV of my camera is about 190 degree, and I'm not going to compute depth map.

**Comment by CanCanZeng** [comment]
I find the answer, the camera model does not matter, the other camera models that support fisheye camera can also be used.

**Comment by xuhao1** [comment]
Autonomous aerial robot using dual‐fisheye cameras, Wenliang Gao, Kaixuan Wang, Wenchao Ding, Fei Gao, Tong Qin, Shaojie Shen, 2020 Journal of Field Robotics (JFR) is a great paper for fisheye cameras
