### ISSUE TITLE
2 Compilation Errors

### ISSUE THREAD

**Issue by fubianhanshu** [xuhao1/VINS-Fisheye#11]
when I compile your code, I get 2 errors
1.
/home/mwy/vins-fisheye/src/VINS-Fisheye/vins_estimator/src/depth_generation/depth_estimator.cpp: In member function ‘cv::Mat DepthEstimator::ComputeDispartiyMap(cv::cuda::GpuMat&, cv::cuda::GpuMat&)’:
/home/mwy/vins-fisheye/src/VINS-Fisheye/vins_estimator/src/depth_generation/depth_estimator.cpp:120:9: error: ‘class sgm::LibSGMWrapper’ has no member named ‘execute’
   sgmp->execute(leftRectify, rightRectify, d_disparity);

LibSGM has been compiled from source.
It's same as @Ali1215 error, I can't understand your solution in that closed issue.Can you explain the solution in more detail?

2.
/home/mwy/vins-fisheye/src/VINS-Fisheye/vins_estimator/src/featureTracker/feature_tracker_pinhole.cpp: At global scope:
/home/mwy/vins-fisheye/src/VINS-Fisheye/vins_estimator/src/featureTracker/feature_tracker_pinhole.cpp:194:1: error: expected ‘}’ at end of input
 }
 ^

Solution：add a ‘}’at the end of file
namespace FeatureTracker { } 
You lost the second '}'

**Comment by fubianhanshu** [comment]
> solved by recompiling libsgm with opencv 3.4, build-opencv-wrapper and build-shared-library options in the cmake file. By default does options are not enabled.

It works! Thank you!

**Comment by Roger-Chuh** [comment]
hi, did you solve the error of missing "vins/FlattenImages.h" ? i am getting the same error, thankyou

**Comment by DavidNY123** [comment]
> hi, did you solve the error of missing "vins/FlattenImages.h" ? i am getting the same error, thankyou

I catkin_make few times（maybe twice or three times）and solved the problem.
