### ISSUE TITLE
loop closure support

### ISSUE THREAD

**Issue by wolf943134497** [xuhao1/VINS-Fisheye#18]
Hi @xuhao1  Thanks for your great works!

Does the project  support loop closure? just use the loop closure code from vins-fusion. Thanks!

**Comment by wolf943134497** [comment]
thanks for your great work and reply. I will try it.

**Comment by XINRUII** [comment]
@wolf943134497 看到这条消息后可以立刻联系我吗，或者去查看你仓库下的 lio-wheel-fusion 工程的 pull request，谢谢！！ Could you please contact me immediately after seeing this message? Or check the pull request of lio-wheel-fusion project under your warehouse, thank you!!

**Comment by XINRUII** [comment]
@wolf943134497    急！！！  看到这条消息后可以立刻联系我吗，或者去查看仓库 lio-wheel-fusion 工程的 pull request，谢谢！！ Could you please contact me immediately after seeing this message? Or check the pull request of lio-wheel-fusion project under your warehouse, thank you!!

**Comment by XINRUII** [comment]
急！！！ 看到这条消息后可以立刻联系我吗，或者去查看仓库 lio-wheel-fusion 工程的 pull request，谢谢！！ Could you please contact me immediately after seeing this message? Or check the pull request of lio-wheel-fusion project under your warehouse, thank you!!

**Comment by XINRUII** [comment]
@wolf943134497  急！！！ 看到这条消息后可以立刻联系我吗，因为您仓库下的工程涉及保密协议，请您立刻联系我 916806487@sjtu.edu.cn，或者去查看仓库 lio-wheel-fusion 工程的 pull request，谢谢！！ Could you please contact me immediately after seeing this message? Or check the pull request of lio-wheel-fusion project under your warehouse, thank you!!

**Comment by XINRUII** [comment]
@wolf943134497 急！！！ 看到这条消息后可以立刻联系我吗，因为您仓库下的工程涉及保密协议，请您立刻联系我 [916806487@sjtu.edu.cn](mailto:916806487@sjtu.edu.cn)，或者去查看仓库 lio-wheel-fusion 工程的 pull request，谢谢！！ Could you please contact me immediately after seeing this message? Or check the pull request of lio-wheel-fusion project under your warehouse, thank you!!

**Comment by wolf943134497** [comment]
> @wolf943134497 急！！！ 看到这条消息后可以立刻联系我吗，因为您仓库下的工程涉及保密协议，请您立刻联系我 [916806487@sjtu.edu.cn](mailto:916806487@sjtu.edu.cn)，或者去查看仓库 lio-wheel-fusion 工程的 pull request，谢谢！！ Could you please contact me immediately after seeing this message? Or check the pull request of lio-wheel-fusion project under your warehouse, thank you!!

已删除工程， 请不要在这么多projrct下面轰炸，把你的commit在所有project下面删除，不要打扰大家
