### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by Ali1215** [xuhao1/VINS-Fisheye#2]
Hello,

When I attempt to compile your code I get the following errors:

/home/nvidia/Desktop/Workspace/src/VINS-Fisheye-1.0/vins_estimator/src/depth_generation/depth_estimator.cpp: In member function ‘cv::Mat DepthEstimator::ComputeDispartiyMap(cv::cuda::GpuMat&, cv::cuda::GpuMat&)’:
/home/nvidia/Desktop/Workspace/src/VINS-Fisheye-1.0/vins_estimator/src/depth_generation/depth_estimator.cpp:96:9: error: ‘class sgm::LibSGMWrapper’ has no member named ‘execute’
   sgmp->execute(leftRectify, rightRectify, d_disparity);

This is my configuration:
NVIDIA Jetson TX2
 L4T 32.3.1 [ JetPack 4.3 ]
   Ubuntu 18.04.4 LTS
   Kernel Version: 4.9.140-tegra
 CUDA 10.0.326
   CUDA Architecture: 6.2
 OpenCV version: 3.4.0
   OpenCV Cuda: YES
 CUDNN: 7.6.3.28
 TensorRT: 6.0.1.10
 Vision Works: 1.6.0.500n
 VPI: 0.1.0

LibSGM has been compiled from source.

**Comment by xuhao1** [comment]
You probably need to recompile libSGM with OpenCV support

**Comment by xuhao1** [comment]
@Ali1215
