### ISSUE TITLE
About a Quaterniond t_rear

### ISSUE THREAD

**Issue by DavidNY123** [xuhao1/VINS-Fisheye#22]
Hello, I think this line 
t_rear = t_rear * Eigen::AngleAxisd(M_PI / 2, Eigen::Vector3d(0, 1, 0));
should be
t_rear = t_right * Eigen::AngleAxisd(M_PI / 2, Eigen::Vector3d(0, 1, 0));
Maybe a mistake?

**Comment by xuhao1** [comment]
@DavidNY123 Thanks! This is a mistake! I fixed it.
