### ISSUE TITLE
double free or corruption (out)

### ISSUE THREAD

**Issue by zhangyangcc** [xuhao1/VINS-Fisheye#26]
@xuhao1 Really appreciate your open source!
I have the following error:
```
double free or corruption (out)
```
The error is produced when node read extrinsic from yaml file. Related code is as follows(in parameters.cpp):
```
cv::Mat cv_T;
fsSettings["body_T_cam1"] >> cv_T;
```
But i don't why. Could you help me to have a look.
Thank you very much!

**Comment by xuhao1** [comment]
@zhangyangcc This is usally happend because you are not correctly setup the config file.

**Comment by dongdong-cai** [comment]
I also encountered this problem, is there a solution?
