### ISSUE TITLE
bearing vector related problem in Estimator::initialStructure

### ISSUE THREAD

**Issue by CanCanZeng** [xuhao1/VINS-Fisheye#3]
Hi, I find that you change undistorted point from 2d point to 3d bearing vector, but in Estimator::initialStructure you still not change the code accordingly. See here https://github.com/xuhao1/VINS-Fisheye/blob/367651a35c582c5b3308009f8071c265970ba403/vins_estimator/src/estimator/estimator.cpp#L780
Might it be a mistake?

**Comment by xuhao1** [comment]
@CanCanZeng For fisheye cameras, only visual-inertial-odometry is supported. The code you show here is for visual-odometry mode of VINS, which is used to initialize VINS when not using an IMU.

**Comment by xuhao1** [comment]
If you want to use these project without IMU, you need to modified initialization code yourself and submit a pull request
