### ISSUE TITLE
What is the purpose of "BACKWARD"?

### ISSUE THREAD

**Issue by engcang** [xuhao1/VINS-Fisheye#6]
Hi.

First I really appreciate that you guys shared this great repo.
By the way, I wonder what the purpose of ["BACKWARD"](https://github.com/xuhao1/VINS-Fisheye/blob/master/vins_estimator/CMakeLists.txt#L9) is.

It seems that this is only included in these two files: [rosNodeTest.cpp](https://github.com/xuhao1/VINS-Fisheye/blob/master/vins_estimator/src/rosNodeTest.cpp#L27), [rosNodelet.cpp](https://github.com/xuhao1/VINS-Fisheye/blob/master/vins_estimator/src/rosNodelet.cpp#L24) but never used over the whole codes.

Even it engenders compile error: 
`No such file or directory #include <backward.hpp>`, after solved the another issue `/usr/bin/ld: cannot find -ldw` by `$ sudo apt install libdw-dev`.

After I commented `set(ENABLE_BACKWARD true)` in the `CMakeLists.txt`, the codes could be built well (but not yet executed).

Thank you in advance.

**Comment by xuhao1** [comment]
@engcang  Backward is a cool project for debugging. Once VINS-Fisheye crashed on robots, it's impossible to debug its with GDB. Backward will print the traceback, which helps you to locate where the bug is.
