### ISSUE TITLE
Could not find a package configuration file provided by "camera_models"

### ISSUE THREAD

**Issue by xjp99v5** [xuhao1/VINS-Fisheye#7]
Hi, Xuhao,

Thanks for your excellent work. I have some questions when catkin_make such kinds of things. When I build this code in a separate ros_ws, it shows:
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "camera_models"
  with any of the following names:

    camera_modelsConfig.cmake
    camera_models-config.cmake

  Add the installation prefix of "camera_models" to CMAKE_PREFIX_PATH or set
  "camera_models_DIR" to a directory containing one of the above files.  If
  "camera_models" provides a separate development package or SDK, be sure it
  has been installed.

When I put these codes with VINS-Fusion, it shows:

RuntimeError: Multiple packages found with the same name "camera_models":
- VINS-Fisheye/camera_models
- VINS-Fusion/camera_models
Multiple packages found with the same name "vins":
- VINS-Fisheye/vins_estimator
- VINS-Fusion/vins_estimator

So, any suggestions.

Thank you.

**Comment by xuhao1** [comment]
Hi @xjp99v5 , sorry for late reply. You may have a try of the latest master branch, which contains the camera models.
And, do not compile VINS-Fisheye in the same workspace with VINS-Fusion

**Comment by xjp99v5** [comment]
Hi, @xuhao1 , thanks for your reply. I have updated the stream. Now a new issue comes.

Errors     << vins:make /home/jiapingntu/VINS-fisheye_ws/logs/vins/build.make.000.log
In file included from /home/jiapingntu/VINS-fisheye_ws/src/VINS-Fisheye/vins_estimator/src/fisheyeNode.cpp:1:0:
/home/jiapingntu/VINS-fisheye_ws/src/VINS-Fisheye/vins_estimator/src/fisheyeNode.hpp:12:10: fatal error: vins/FlattenImages.h: No such file or directory
 #include "vins/FlattenImages.h"
          ^~~~~~~~~~~~~~~~~~~~~~

**Comment by xuhao1** [comment]
It's a bug of compile system of ROS, catkin_make few times solves the problem.

**Comment by xjp99v5** [comment]
> It's a bug of compile system of ROS, catkin_make few times solves the problem.

Thanks. I have solved this problem. And where I can find this fisheye_split.launch file.
Thank you.

**Comment by xuhao1** [comment]
@xjp99v5 Use fisheye_node.launch instead
